# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
downloadcache = {toxworkdir}/.cache
env_list =
    py313-django42
    py313-django50
    py313-django51
    py313-django52

[testenv]
commands = pytest tests --tb=short -x --pdb
setenv =
    DJANGO_SETTINGS_MODULE = sampleproject.settings
    PYTHONPATH = {toxinidir}:{toxinidir}/sampleproject

[base]
deps =
    pytest-django
    webtest
    django-webtest
    pytest
    lxml
    cssselect
    mock
    Pillow
    setuptools

[testenv:py313-django42]
basepython = python3.13
deps =
    django>=4.2,<5.0
    {[base]deps}

[testenv:py313-django50]
basepython = python3.13
deps =
    django>=5.0,<5.1
    {[base]deps}

[testenv:py313-django51]
basepython = python3.13
deps =
    django>=5.1,<5.2
    {[base]deps}

[testenv:py313-django52]
basepython = python3.13
deps =
    django>=5.2,<6.0
    {[base]deps}